FROM arm64v8/ubuntu

# Dependencies
RUN apt-get update \
  && apt-get install -y \
  wget \
  && rm -rf /var/lib/apt/lists/*

# Tini for signal processing and zombie killing
# https://github.com/krallin/tini
ENV TINI_VERSION 0.18.0
RUN wget https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini_${TINI_VERSION}.deb
RUN dpkg -i tini_${TINI_VERSION}.deb

ENTRYPOINT ["tini", "--"]
